# Generated by Django 5.2.5 on 2025-08-31 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
    ]
