# Generated by Django 5.2.5 on 2025-08-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
