# Generated by Django 5.2.5 on 2025-08-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_remove_member_affiliation_remove_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='description_image',
            field=models.CharField(blank=True, choices=[('bands/images/undefined66_des.jpg', 'Undefined66 소개'), ('bands/images/what4ever_des.jpeg', 'WHAT4EVER 소개'), ('bands/images/rhythm_des.jpeg', '리듬군단 소개'), ('bands/images/release_des.jpeg', '릴리즈 소개'), ('bands/images/baedangjoo_des.jpg', '배당주 소개'), ('bands/images/entrophy_des.jpeg', '엔트로피 소개'), ('bands/images/jazzpeople_des.jpeg', '재찾사 소개'), ('bands/images/firstint_des.jpg', '초심 소개'), ('bands/images/blue_des.png', '파란 소개'), ('bands/images/hathow9y_des.jpeg', '해쏘웨이 소개')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='profile_image',
            field=models.CharField(blank=True, choices=[('bands/images/blue_profile.png', '파란 프로필'), ('bands/images/undefined66_profile.png', 'Undefined66 프로필'), ('bands/images/what4ever_profile.png', 'WHAT4EVER 프로필'), ('bands/images/release_profile.png', '릴리즈 프로필'), ('bands/images/jazzpeople_profile.jpg', '재찾사 프로필'), ('bands/images/firstint_profile.png', '초심 프로필')], max_length=200, null=True),
        ),
    ]
