# Generated by Django 5.2.5 on 2025-08-31 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_alter_band_description_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'ordering': ['id']},
        ),
    ]
