# Generated by Django 5.2.5 on 2025-09-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_alter_band_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='profile_image',
            field=models.CharField(blank=True, choices=[('bands/images/blue_profile.png', '파란 프로필'), ('bands/images/undefined66_profile.png', 'Undefined66 프로필'), ('bands/images/what4ever_profile.png', 'WHAT4EVER 프로필'), ('bands/images/release_profile.png', '릴리즈 프로필'), ('bands/images/jazzpeople_profile.jpg', '재찾사 프로필'), ('bands/images/firstint_profile.png', '초심 프로필'), ('bands/images/rhythm_profile.jpg', '리듬군단 프로필')], max_length=200, null=True),
        ),
    ]
